# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zmb6z46us0jGUse68HPHPsOMD0NHrB2B
"""

def quarter_of(month):
    month = list()
 

i = int(input("Введите номер месяца: "))
quarter_of(month) == (
    'месяц 1 (январь) является частью первого квартала' ,
    'месяц 2 (февраль) является частью первого квартала',
    'месяц 3 (март) является частью первого квартала',
    'месяц 4 (апрель) является частью второго квартала',
    'месяц 5 (май) является частью второго квартала',
    'месяц 6 (июнь) является частью второго квартала',
    'месяц 7 (июль) является частью третьего квартала',
    'месяц 8 (август) является частью третьего квартала',
    'месяц 9 (сентябрь) является частью третьего квартала',
    'месяц 10(октябрь) является частью четвертого квартала',
    'месяц 11(ноябрь) является частью четвертого квартала',
    'месяц 12(декабрь) является частью четвертого квартала '
)
if i==1:
    print (month[i-1])
elif i==2:
    print (month[i-1])
elif i==3:
    print (month[i-1])
elif i==4:
    print (month[i-1])
elif i==5:
    print (month[i-1])
elif i==6:
    print (month[i-1])
elif i==7:
    print (month[i-1])
elif i==8:
    print (month[i-1])
elif i==9:
    print (month[i-1])
elif i==10:
    print (month[i-1])
elif i==11:
    print (month[i-1])
elif i==12:
    print (month[i-1])
else:
    print('Ошибка!')