# -*- coding: utf-8 -*-
"""22_06_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSqeqiZM-LrL9mjG-Zp8zbb9M-m02Ak8
"""

import pandas as pd
import sqlite3

con1 = sqlite3.connect("Students.db")
tablestud = pd.read_sql("SELECT * FROM Students",con1)
print (tablestud)
con2 = sqlite3.connect("teachers.db")
tablestud.to_sql("Students",con2, index = False)

import sqlite3
def get_stud(student_id):
  con = sqlite3.connect("teachers.db")
  cur = con.cursor()
  query = """SELECT * FROM School JOIN Students ON School.School_id = Students.School_id WHERE Students.Student_id = ?"""
  cur.execute(query,(student_id,))
  rec = cur.fetchall()
  print (rec)

get_stud(201)

